/*-----------------------------------------01.데이터 생성하기*/

PROC SQL;
CREATE TABLE GOOD_DM AS 
SELECT BD_ITEM_LCLS_CD AS 대분류코드
          ,BD_ITEM_LCLS_NM AS 대분류명
          ,BD_ITEM_MCLS_CD AS LINE_CD
          ,BD_ITEM_MCLS_NM AS LINE_NM
          ,BD_ITEM_SCLS_CD AS CLASS_CD
		  ,BD_ITEM_SCLS_NM AS CLASS_NM
		  ,BD_ITEM_DCLS_CD AS 세분류코드
		  ,BD_ITEM_DCLS_NM AS 세분류명
          ,COMPRESS(BD_ITEM_CD) AS GOODS_CD
          ,COMPRESS(BD_ITEM_NM) AS GOODS_NM
  FROM GSSELDW.TB_DM_BD_ITEM_BASE
  WHERE BIZU_CD='1' /*편의점코드*/
;
QUIT;


%LET ST_DATE1 = '20210316'; /*데이터 추출 시작일*/ 
%LET END_DATE1 = '20210331'; /*데이터 추출 마감일*/
%LET LINE1=39 ;
%LET YYYYMMDD=20210316 ;
%LET BIZ1=A1 ;
	
	PROC SQL ;
	CREATE TABLE SALE_DAY1 AS
	SELECT ORIGIN_BIZPL_CD ,COUNT(DISTINCT OPER_DT ) AS SALE_DAY
	FROM GSSELDW.TB_FT_CVS_TR_HDR 
	WHERE OPER_DT BETWEEN &ST_DATE1 AND &END_DATE1
GROUP BY 1;
	QUIT; 

%MACRO AMT(LINE=,BIZ=);
PROC SQL;
CREATE TABLE AMT_LINE_&BIZ. AS  /*점별 카테고리별 판매 데이터 생성*/
SELECT C.BIZPL_CL_DIV_CD
            ,A.ORIGIN_BIZPL_CD
            ,COMPRESS(A.ORIGIN_BIZPL_CD||A.OPER_DT||A.POS_NO||PUT(A.SALE_SEQ,VARCHAR6.)) AS KEY
            ,B.LINE_CD
            ,A.GOODS_CD
            ,D.SALE_DAY
            ,SUM(A.SALE_QTY) AS QTY
            ,SUM((A.DC_PRC*A.SALE_QTY)-A.MBR_DC_AMT-A.SALE_VAT-A.PRMT_DC_AMT) AS AMT
            ,CALCULATED QTY / SALE_DAY AS DQTY
            ,CALCULATED AMT / SALE_DAY AS DAMT
FROM GSSELDW.TB_FT_CVS_TR_ITEM AS A
INNER JOIN GOOD_DM AS B ON A.GOODS_CD = B.GOODS_CD AND B.LINE_CD = "&LINE"
INNER JOIN (SELECT DISTINCT BIZPL_CL_DIV_CD, ORIGIN_BIZPL_CD FROM ZTC_LIB.LINE_202005
                    WHERE GOOD_CLS1CD = "&LINE" AND BIZPL_CL_DIV_CD = "&BIZ") AS C ON A.ORIGIN_BIZPL_CD = C.ORIGIN_BIZPL_CD
LEFT JOIN SALE_DAY1 AS D ON A.ORIGIN_BIZPL_CD = D.ORIGIN_BIZPL_CD
WHERE 1=1
AND A.SALE_SP IN ('1','2','3','4','5','6','9','A')
AND A.DEAL_SP IN ('01','33','61')
AND A.SKU_CANCEL_YN = 'N'
AND A.OPER_DT BETWEEN &ST_DATE1. AND &END_DATE1.
/*&ST_DATE AND &END_DATE*/
GROUP BY 1,2,3,4,5,6
;
QUIT;
%MEND ;


%AMT(LINE=39,BIZ=A1);

DATA SUSER40.AMTRAW_LINE&LINE1._&BIZ1._&YYYYMMDD. ;
SET AMT_LINE_A1 ;
RUN;



%AMT(LINE=39,BIZ=A2);%AMT(LINE=39,BIZ=A3);%AMT(LINE=39,BIZ=A4);
%AMT(LINE=39,BIZ=B1);%AMT(LINE=39,BIZ=B2);%AMT(LINE=39,BIZ=B3);
%AMT(LINE=39,BIZ=C1);%AMT(LINE=39,BIZ=C2);%AMT(LINE=39,BIZ=C3);
%AMT(LINE=39,BIZ=D1);%AMT(LINE=39,BIZ=E1);

